#updated by kobe, 2008,1,23
#--------------------------------------------------------------------------------------------------
CC = gcc -Wall -g -O3
CXX= g++ -Wall -g -O3
CXXFLAGS=-I/usr/home/conglei/DCF/include -I. -L/usr/local/lib -L/usr/lib -L/usr/home/conglei/DCF/lib
LIBS=-lpthread -ltransdoc -lmonitor -ldispatch -lcommon -ldl -levent
#--------------------------------------------------------------------------------------------------
OUTPUTFILES=reducer
all: $(OUTPUTFILES)
.SUFFIXES: .o .cpp .hpp
#--------------------------------------------------------------------------------------------------

reducer: main.o Common.o ReducerConfigInfor.o
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LIBS)
.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<
.c.o:
	$(CC) $(CXXFLAGS) -c $<
#--------------------------------------------------------------------------------------------------

clean:
	rm -rf $(OUTPUTFILES) *.o *.so *.a
